var LocalHints, TypingProtector, WaitForEnter,
  __slice = [].slice,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;



var isSelectable = function(element) {
  var unselectableTypes;
  if (!(element instanceof Element)) {
    return false;
  }
  unselectableTypes = ["button", "checkbox", "color", "file", "hidden", "image", "radio", "reset", "submit"];
  return (element.nodeName.toLowerCase() === "input" && unselectableTypes.indexOf(element.type) === -1) || element.nodeName.toLowerCase() === "textarea" || element.isContentEditable;
}




var isString = function(obj) {
  return typeof obj === 'string' || obj instanceof String;
}

var getScrollingElement = function() {
  var ref;
  return (ref = document.scrollingElement) != null ? ref : document.body;
};

var getDimension = function(el, direction, amount) {
  var name;
  if (isString(amount)) {
    name = amount;
    if (name === 'viewSize' && el === getScrollingElement()) {
      if (direction === 'x') {
        return window.innerWidth;
      } else {
        return window.innerHeight;
      }
    } else {
      return el[scrollProperties[direction][name]];
    }
  } else {
    return amount;
  }
};


var scrollProperties = {
  x: {
    axisName: 'scrollLeft',
    max: 'scrollWidth',
    viewSize: 'clientWidth'
  },
  y: {
    axisName: 'scrollTop',
    max: 'scrollHeight',
    viewSize: 'clientHeight'
  }
};

var performScroll = function(element, direction, amount) {
  var axisName, before;
  axisName = scrollProperties[direction].axisName;
  before = element[axisName];
  element[axisName] += amount;
  return element[axisName] !== before;
};

var shouldScroll = function(element, direction) {
  var computedStyle, ref;
  computedStyle = window.getComputedStyle(element);
  if (computedStyle.getPropertyValue("overflow-" + direction) === "hidden") {
    return false;
  }
  if ((ref = computedStyle.getPropertyValue("visibility")) === "hidden" || ref === "collapse") {
    return false;
  }
  if (computedStyle.getPropertyValue("display") === "none") {
    return false;
  }
  return true;
};

var doesScroll = function(element, direction, amount, factor) {
  var delta;
  delta = factor * getDimension(element, direction, amount) || -1;
  delta = Math.sign(delta);
  return performScroll(element, direction, delta) && performScroll(element, direction, -delta);
};

var isScrollableElement = function(element, direction, amount, factor) {
  if (direction == null) {
    direction = "y";
  }
  if (amount == null) {
    amount = 1;
  }
  if (factor == null) {
    factor = 1;
  }
  return doesScroll(element, direction, amount, factor) && shouldScroll(element, direction);
};

// ---
// generated by coffee-script 1.9.2






var getVisibleClickable = function(element) {
  /*
   * Get the tag name.  However, `element.tagName` can be an element (not a string, see #2035), so we guard
   * against that.
   */
  var actionName, areas, areasAndRects, clientRect, contentEditable, eventType, imgClientRects, isClickable, jsactionRule, jsactionRules, map, mapName, namespace, onlyHasTabIndex, possibleFalsePositive, reason, role, ruleSplit, tabIndex, tabIndexValue, tagName, visibleElements, _base, _i, _len, _ref, _ref1, _ref10, _ref11, _ref12, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
  tagName = (_ref = typeof (_base = element.tagName).toLowerCase === "function" ? _base.toLowerCase() : void 0) != null ? _ref : "";
  isClickable = false;
  onlyHasTabIndex = false;
  possibleFalsePositive = false;
  visibleElements = [];
  reason = null;

  // Insert area elements that provide click functionality to an img.
  // TODO bonus
  // if (tagName === "img") {
  //   mapName = element.getAttribute("usemap");
  //   if (mapName) {
  //     imgClientRects = element.getClientRects();
  //     mapName = mapName.replace(/^#/, "").replace("\"", "\\\"");
  //     map = document.querySelector("map[name=\"" + mapName + "\"]");
  //     if (map && imgClientRects.length > 0) {
  //       areas = map.getElementsByTagName("area");
  //       areasAndRects = DomUtils.getClientRectsForAreas(imgClientRects[0], areas);
  //       visibleElements.push.apply(visibleElements, areasAndRects);
  //     }
  //   }
  // }

  // Check aria properties to see if the element should be ignored.
  if (((_ref1 = (_ref2 = element.getAttribute("aria-hidden")) != null ? _ref2.toLowerCase() : void 0) === "" || _ref1 === "true") ||
    ((_ref3 = (_ref4 = element.getAttribute("aria-disabled")) != null ? _ref4.toLowerCase() : void 0) === "" || _ref3 === "true")) {
      return []; // This element should never have a link hint.
    }

  // Check for AngularJS listeners on the element.
  if (this.checkForAngularJs == null) {
    this.checkForAngularJs = (function() {
      var angularElements, ngAttributes, prefix, separator, _i, _j, _len, _len1, _ref5, _ref6;
      angularElements = document.getElementsByClassName("ng-scope");
      if (angularElements.length === 0) {
        return function() {
          return false;
        };
      } else {
        ngAttributes = [];
        _ref5 = ['', 'data-', 'x-'];
        for (_i = 0, _len = _ref5.length; _i < _len; _i++) {
          prefix = _ref5[_i];
          _ref6 = ['-', ':', '_'];
          for (_j = 0, _len1 = _ref6.length; _j < _len1; _j++) {
            separator = _ref6[_j];
            ngAttributes.push(prefix + "ng" + separator + "click");
          }
        }
        return function(element) {
          var attribute, _k, _len2;
          for (_k = 0, _len2 = ngAttributes.length; _k < _len2; _k++) {
            attribute = ngAttributes[_k];
            if (element.hasAttribute(attribute)) {
              return true;
            }
          }
          return false;
        };
      }
    })();
  }
  isClickable || (isClickable = this.checkForAngularJs(element));


  // Check for attributes that make an element clickable regardless of its tagName.
  if (element.hasAttribute("onclick") || (role = element.getAttribute("role")) && ((_ref5 = role.toLowerCase()) === "button" || _ref5 === "tab" || _ref5 === "link" || _ref5 === "checkbox" || _ref5 === "menuitem" || _ref5 === "menuitemcheckbox" || _ref5 === "menuitemradio") || (contentEditable = element.getAttribute("contentEditable")) && ((_ref6 = contentEditable.toLowerCase()) === "" || _ref6 === "contenteditable" || _ref6 === "true")) {
    isClickable = true;
  }


  // Check for jsaction event listeners on the element.
  if (!isClickable && element.hasAttribute("jsaction")) {
    jsactionRules = element.getAttribute("jsaction").split(";");
    for (_i = 0, _len = jsactionRules.length; _i < _len; _i++) {
      jsactionRule = jsactionRules[_i];
      ruleSplit = jsactionRule.trim().split(":");
      if ((1 <= (_ref7 = ruleSplit.length) && _ref7 <= 2)) {
        _ref8 = ruleSplit.length === 1 ? ["click"].concat(__slice.call(ruleSplit[0].trim().split(".")), ["_"]) : [ruleSplit[0]].concat(__slice.call(ruleSplit[1].trim().split(".")), ["_"]), eventType = _ref8[0], namespace = _ref8[1], actionName = _ref8[2];
        isClickable || (isClickable = eventType === "click" && namespace !== "none" && actionName !== "_");
      }
    }
  }

  // Check for tagNames which are natively clickable.
  switch (tagName) {
    case "a":
      isClickable = true;
      break;
    case "textarea":
      isClickable || (isClickable = !element.disabled && !element.readOnly);
      break;
    case "input":
      isClickable || (isClickable = !(((_ref9 = element.getAttribute("type")) != null ? _ref9.toLowerCase() : void 0) === "hidden" || element.disabled || (element.readOnly && isSelectable(element))));
      break;
    case "button":
    case "select":
      isClickable || (isClickable = !element.disabled);
      break;
    case "label":
      isClickable || (isClickable = (element.control != null) && !element.control.disabled && (this.getVisibleClickable(element.control)).length === 0);
      break;
    case "body":
      isClickable || (isClickable = element === document.body && !windowIsFocused() && window.innerWidth > 3 && window.innerHeight > 3 && ((_ref10 = document.body) != null ? _ref10.tagName.toLowerCase() : void 0) !== "frameset" ? reason = "Frame." : void 0);
      isClickable || (isClickable = element === document.body && windowIsFocused() && isScrollableElement(element) ? reason = "Scroll." : void 0);
      break;
    case "img":
      isClickable || (isClickable = (_ref11 = element.style.cursor) === "zoom-in" || _ref11 === "zoom-out");
      break;
    case "div":
    case "ol":
    case "ul":
      isClickable || (isClickable = element.clientHeight < element.scrollHeight && isScrollableElement(element) ? reason = "Scroll." : void 0);
      break;
    case "details":
      isClickable = true;
      reason = "Open.";
  }

  /*
   * NOTE(smblott) Disabled pending resolution of #2997.
   * # Detect elements with "click" listeners installed with `addEventListener()`.
   * isClickable ||= element.hasAttribute "_vimium-has-onclick-listener"

   * An element with a class name containing the text "button" might be clickable.  However, real clickables
   * are often wrapped in elements with such class names.  So, when we find clickables based only on their
   * class name, we mark them as unreliable.
   */
  if (!isClickable && 0 <= ((_ref12 = element.getAttribute("class")) != null ? _ref12.toLowerCase().indexOf("button") : void 0)) {
    possibleFalsePositive = isClickable = true;
  }

  /*
   * Elements with tabindex are sometimes useful, but usually not. We can treat them as second class
   * citizens when it improves UX, so take special note of them.
   */
  tabIndexValue = element.getAttribute("tabindex");
  tabIndex = tabIndexValue === "" ? 0 : parseInt(tabIndexValue);
  if (!(isClickable || isNaN(tabIndex) || tabIndex < 0)) {
    isClickable = onlyHasTabIndex = true;
  }
  if (isClickable) {
    //clientRect = DomUtils.getVisibleClientRect(element, true);
    //if (clientRect !== null) {
    visibleElements.push({
      element: element,
      //rect: clientRect,
      secondClassCitizen: onlyHasTabIndex,
      possibleFalsePositive: possibleFalsePositive,
      reason: reason
    });
    //}
  }
  return visibleElements;
};



// /*
//  * Returns all clickable elements that are not hidden and are in the current viewport, along with rectangles
//  * at which (parts of) the elements are displayed.
//  * In the process, we try to find rects where elements do not overlap so that link hints are unambiguous.
//  * Because of this, the rects returned will frequently *NOT* be equivalent to the rects for the whole
//  * element.
//  */
// var getLocalHints = function(requireHref) {
//   var descendantsToCheck, element, elements, hint, left, localHints, negativeRect, nonOverlappingElements, position, rects, top, visibleElement, visibleElements, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1;
//   // We need documentElement to be ready in order to find links
//   if (!document.documentElement) {
//     return [];
//   }
//
//   /*
//    * The order of elements here is important; they should appear in the order they are in the DOM, so that
//    * we can work out which element is on top when multiple elements overlap. Detecting elements in this loop
//    * is the sensible, efficient way to ensure this happens.
//    * NOTE(mrmr1993): Our previous method (combined XPath and DOM traversal for jsaction) couldn't provide
//    * this, so it's necessary to check whether elements are clickable in order, as we do below.
//    */
//   elements = document.documentElement.getElementsByTagName("*");
//   visibleElements = [];
//   for (_i = 0, _len = elements.length; _i < _len; _i++) {
//     element = elements[_i];
//     if (!(requireHref && !element.href)) {
//       visibleElement = this.getVisibleClickable(element);
//       visibleElements.push.apply(visibleElements, visibleElement);
//     }
//   }
//
//   // Traverse the DOM from descendants to ancestors, so later elements show above earlier elements.
//   visibleElements = visibleElements.reverse();
//
//   /*
//    * Filter out suspected false positives.  A false positive is taken to be an element marked as a possible
//    * false positive for which a close descendant is already clickable.  False positives tend to be close
//    * together in the DOM, so - to keep the cost down - we only search nearby elements.  NOTE(smblott): The
//    * visible elements have already been reversed, so we're visiting descendants before their ancestors.
//    */
//   // descendantsToCheck = [1, 2, 3]; // This determines how many descendants we're willing to consider.
//   // visibleElements = (function() {
//   //   var _j, _len1, _results;
//   //   _results = [];
//   //   for (position = _j = 0, _len1 = visibleElements.length; _j < _len1; position = ++_j) {
//   //     element = visibleElements[position];
//   //     if (element.possibleFalsePositive && (function() {
//   //       var candidateDescendant, index, _, _k, _len2;
//   //       index = Math.max(0, position - 6);  // This determines how far back we're willing to look
//   //       while (index < position) {
//   //         candidateDescendant = visibleElements[index].element;
//   //         for (_k = 0, _len2 = descendantsToCheck.length; _k < _len2; _k++) {
//   //           _ = descendantsToCheck[_k];
//   //           candidateDescendant = candidateDescendant != null ? candidateDescendant.parentElement : void 0;
//   //           if (candidateDescendant === element.element) {
//   //             return true;
//   //           }
//   //         }
//   //         index += 1;
//   //       }
//   //       return false; // This is not a false positive.
//   //     })()) {
//   //       continue;
//   //     }
//   //     _results.push(element);
//   //   }
//   //   return _results;
//   // })();
//
//
//   /*
//    * TODO(mrmr1993): Consider z-index. z-index affects behaviour as follows:
//    *  * The document has a local stacking context.
//    *  * An element with z-index specified
//    *    - sets its z-order position in the containing stacking context, and
//    *    - creates a local stacking context containing its children.
//    *  * An element (1) is shown above another element (2) if either
//    *    - in the last stacking context which contains both an ancestor of (1) and an ancestor of (2), the
//    *      ancestor of (1) has a higher z-index than the ancestor of (2); or
//    *    - in the last stacking context which contains both an ancestor of (1) and an ancestor of (2),
//    *        + the ancestors of (1) and (2) have equal z-index, and
//    *        + the ancestor of (1) appears later in the DOM than the ancestor of (2).
//    *
//    * Remove rects from elements where another clickable element lies above it.
//    */
//   localHints = nonOverlappingElements = [];
//   while (visibleElement = visibleElements.pop()) {
//     // Subtract negativeRect from every rect in rects, and concatenate the arrays of rects that result.
//     rects = [visibleElement.rect];
//     for (_j = 0, _len1 = visibleElements.length; _j < _len1; _j++) {
//       negativeRect = visibleElements[_j].rect;
//       rects = (_ref = []).concat.apply(_ref, rects.map(function(rect) {
//         return Rect.subtract(rect, negativeRect);
//       }));
//     }
//     if (rects.length > 0) {
//       nonOverlappingElements.push(extend(visibleElement, {
//         rect: rects[0]
//       }));
//     } else {
//       if (!visibleElement.secondClassCitizen) {
//         /*
//          * Every part of the element is covered by some other element, so just insert the whole element's
//          * rect. Except for elements with tabIndex set (second class citizens); these are often more trouble
//          * than they're worth.
//          * TODO(mrmr1993): This is probably the wrong thing to do, but we don't want to stop being able to
//          * click some elements that we could click before.
//          */
//         nonOverlappingElements.push(visibleElement);
//       }
//     }
//   }
//   // Position the rects within the window
//   //_ref1 = DomUtils.getViewportTopLeft(), top = _ref1.top, left = _ref1.left;
//   //for (_k = 0, _len2 = nonOverlappingElements.length; _k < _len2; _k++) {
//   //  hint = nonOverlappingElements[_k];
//   //  hint.rect.top += top;
//   //  hint.rect.left += left;
//   //}
//   //if (Settings.get("filterLinkHints")) {
//   for (_l = 0, _len3 = localHints.length; _l < _len3; _l++) {
//     hint = localHints[_l];
//     //extend(hint, this.generateLinkText(hint));
//   }
//   //}
//   return localHints;
// }








var candidates = Array.from(document.querySelectorAll('body :not(script)'))
var targets = candidates
  .map(getVisibleClickable)
  .filter(s=>s.length>0)
  .map(s=>s[0].element)

console.log(targets)
console.log(targets.map(el=>el.getAttribute('data-xid')))
